const router = require('express').Router();
const { marked } = require('marked');
const sanitizeHtml = require('sanitize-html');

// Configure marked for safe rendering
marked.setOptions({
  gfm: true,
  breaks: true,
});

// Allowed HTML config for sanitize-html
const SANITIZE_OPTIONS = {
  allowedTags: [
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'p', 'br', 'hr',
    'strong', 'em', 'b', 'i', 'u', 's', 'del',
    'ul', 'ol', 'li',
    'blockquote', 'pre', 'code',
    'a', 'img',
    'figure', 'figcaption',
    'table', 'thead', 'tbody', 'tr', 'th', 'td',
    'div', 'span',
  ],
  allowedAttributes: {
    a: ['href', 'title', 'target', 'rel'],
    img: ['src', 'alt', 'title', 'loading', 'width', 'height'],
    code: ['class'],
    pre: ['class'],
    div: ['class'],
    span: ['class'],
    blockquote: ['class'],
    td: ['colspan', 'rowspan'],
    th: ['colspan', 'rowspan'],
  },
  allowedSchemes: ['https', 'http', 'mailto'],
  transformTags: {
    a: (tagName, attribs) => ({
      tagName,
      attribs: {
        ...attribs,
        rel: 'noopener noreferrer',
        ...(attribs.href && !attribs.href.startsWith('/') ? { target: '_blank' } : {}),
      },
    }),
  },
};

/**
 * Helper: format Firestore post document for templates
 */
function formatPost(doc) {
  const data = doc.data();
  const createdAt = data.createdAt?.toDate?.() || new Date(data.createdAt) || new Date();
  const rawContent = data.content || '';

  let contentHtml;
  if (data.contentType === 'html') {
    contentHtml = sanitizeHtml(rawContent, SANITIZE_OPTIONS);
  } else {
    contentHtml = marked.parse(rawContent);
  }

  // Word count: strip tags for HTML content
  const wordCount = rawContent.replace(/<[^>]*>/g, '').split(/\s+/).filter(Boolean).length;

  return {
    id: doc.id,
    title: data.title || 'Untitled',
    slug: data.slug,
    excerpt: data.excerpt || '',
    content: rawContent,
    contentHtml,
    contentType: data.contentType || 'markdown',
    coverImage: data.coverImage || null,
    tags: data.tags || [],
    published: data.published || false,
    autoGenerated: data.autoGenerated || false,
    readTime: Math.max(1, Math.ceil(wordCount / 200)),
    dateFormatted: createdAt.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }),
    dateISO: createdAt.toISOString(),
    createdAt,
  };
}

// ── Blog listing page ──
router.get('/', async (req, res) => {
  try {
    const { db } = require('../firebase-config');

    const postsSnap = await db.collection('posts')
      .where('published', '==', true)
      .get();

    const posts = postsSnap.docs
      .map(formatPost)
      .sort((a, b) => b.createdAt - a.createdAt);

    const structuredData = {
      '@context': 'https://schema.org',
      '@type': 'Blog',
      name: 'Meesam Gardezi Blog',
      description: 'Writing about Flutter, full-stack development, SaaS building, AI, and shipping products solo.',
      url: `${res.locals.baseUrl}/blog`,
      author: {
        '@type': 'Person',
        name: 'Meesam Gardezi',
      },
      blogPost: posts.map(p => ({
        '@type': 'BlogPosting',
        headline: p.title,
        url: `${res.locals.baseUrl}/blog/${p.slug}`,
        datePublished: p.dateISO,
      })),
    };

    res.render('blog', {
      title: 'Blog — Meesam Gardezi',
      description: 'Thoughts on Flutter, full-stack development, SaaS, AI, and building products solo.',
      ogType: 'blog',
      structuredData,
      posts,
    });
  } catch (error) {
    console.error('Blog listing error:', error);
    res.render('blog', {
      title: 'Blog — Meesam Gardezi',
      description: 'Thoughts on Flutter, full-stack development, SaaS, AI, and building products solo.',
      posts: [],
    });
  }
});

// ── Single blog post ──
router.get('/:slug', async (req, res) => {
  try {
    const { db } = require('../firebase-config');

    const postsSnap = await db.collection('posts')
      .where('slug', '==', req.params.slug)
      .get();

    const matchDoc = postsSnap.docs.find(d => d.data().published === true);
    if (!matchDoc) {
      return res.status(404).render('404', {
        title: '404 — Post Not Found | Meesam Gardezi',
        description: 'The blog post you are looking for does not exist.',
      });
    }

    const post = formatPost(matchDoc);

    const structuredData = {
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      headline: post.title,
      description: post.excerpt,
      url: `${res.locals.baseUrl}/blog/${post.slug}`,
      datePublished: post.dateISO,
      dateModified: post.dateISO,
      author: {
        '@type': 'Person',
        name: 'Meesam Gardezi',
        url: res.locals.baseUrl,
      },
      publisher: {
        '@type': 'Person',
        name: 'Meesam Gardezi',
      },
      ...(post.coverImage && { image: post.coverImage }),
      keywords: post.tags.join(', '),
    };

    res.render('blog-post', {
      title: `${post.title} — Meesam Gardezi`,
      description: post.excerpt || `Read "${post.title}" by Meesam Gardezi`,
      ogType: 'article',
      ogImage: post.coverImage,
      structuredData,
      post,
    });
  } catch (error) {
    console.error('Blog post error:', error);
    res.status(500).render('404', {
      title: 'Error | Meesam Gardezi',
      description: 'Something went wrong loading this post.',
    });
  }
});

module.exports = router;
